"""schedule item displacement fields

Revision ID: 47802012c19c
Revises: 3f6f75368c30
Create Date: 2026-09-29 23:39:00.455527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47802012c19c'
down_revision: Union[str, Sequence[str], None] = '3f6f75368c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_items', sa.Column('displaced_by_task_id', sa.UUID(), nullable=True))
    op.add_column('schedule_items', sa.Column('displacement_reason', sa.String(), nullable=True))
    op.add_column('schedule_items', sa.Column('original_start_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'schedule_items', 'tasks', ['displaced_by_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_items', type_='foreignkey')
    op.drop_column('schedule_items', 'original_start_time')
    op.drop_column('schedule_items', 'displacement_reason')
    op.drop_column('schedule_items', 'displaced_by_task_id')
    # ### end Alembic commands ###
